### ISSUE TITLE
Missing latest version on packagist

### ISSUE THREAD

**Issue by zkabic** [reactphp/datagram#36]
Currently, installing via composer doesn't install latest changes from repo.  Changes from  [this](https://github.com/reactphp/datagram/commit/7db9e9779107d2ae0bfe017b6c90eab1d29a4eee) commit are not submitted to packages.ogr.

Hope you'll fix this soon :-)

**Comment by clue** [comment]
@zkabic Thanks for the reminder :-)

Will release once #38 and PHP support is in :shipit:
