### ISSUE TITLE
Multiple clients connections on same port?

### ISSUE THREAD

**Issue by andevit** [reactphp/datagram#40]
Hi guys, 
this is my first time implementing a UDP server. 

I would like to understand if this can handle hundreds of incoming connections per second on the same port. 
Is there something I can do to lose fewer packets?

Thanks!

**Comment by WyriHaximus** [comment]
Keep in mind that in UPD there is no concept like connections as TCP has. So there is no message/package retries build in, that's something you'd have to take care of. So any failed message/package has to be retried or the system has to be robust enough that missed messages are acceptable and state can be recovered through new messages coming in.

**Comment by andevit** [comment]
All clear thanks. 
My doubt was whether having multiple instances of the server running could limit packet loss. 

Consider that there are 100 clients sending UDP packets every second.
