### ISSUE TITLE
Support for AF_UNIX/SOCK_SEQPACKET sockets

### ISSUE THREAD

**Issue by gdejong** [reactphp/datagram#43]
Hi!

Is there a way to use this project to create a Server that can accept socket connections created using `AF_UNIX/SOCK_SEQPACKET`?

This might not work with the `StreamSelectLoop` since these sockets work with `socket_select` rather than `stream_select`.

Some resources:
- https://www.php.net/manual/en/function.socket-create.php
- https://www.php.net/manual/en/function.socket-select.php
- https://www.hitchhikersguidetolearning.com/2020/04/26/sequenced-socket-sock_seqpacket-connection/
- http://urchin.earth.li/~twic/Sequenced_Packets_Over_Ordinary_TCP.html

**Comment by SimonFrings** [comment]
Hey @gdejong, thanks for bringing this up :+1:

In short: There's no implementation for that at the moment. It's definitely a cool feature but I don't think that this should be a part of react/datagram, it would better fit into [react/socket](https://github.com/reactphp/socket). There also exists a similar ticket: [react/socket#73](https://github.com/reactphp/socket/issues/73).

We don't have a demand for this feature at the moment but PRs are always more than welcome ^^

**Comment by clue** [comment]
@gdejong I agree, this is definitely valuable and it looks like this would be a nice candidate for reactphp/socket! :+1:

This is definitely doable and if anybody feels like filing a PR, I can definitely see us adding this. If there's enough demand, we might also look into this in the future (feel free to drop me a mail if this is a commercial project) :+1: 

As much as I'd love to work on this myself, there are currently no immediate plans to build this from my end (no demand at the moment and more important outstanding issues currently). If you need this for a commercial project and you want to help sponsor this feature, feel free to reach out and I'm happy to take a look.
