### ISSUE TITLE
Stream Video

### ISSUE THREAD

**Issue by Dumra** [reactphp/datagram#9]
Have a nice day. Thanks for a good package. 
But i have some question 2 u.
Can i get a video stream  (create server with open UDP socket) from an other server (need UDP protocol) and output it for some users (clients) via e.g. Ratchet in real-time?
And save some length of this stream?
Thanks.

**Comment by clue** [comment]
> Can i get a video stream (create server with open UDP socket) from an other server (need UDP protocol) 

Absolutely! This is low-level datagram (UDP) socket component which can be used to transport any kind of data.

> […] output it for some users (clients) via e.g. Ratchet in real-time? And save some length of this stream?

Technically yes, practically probably not. Either way, this is way beyond the scope of this library. This library allows you to consume (or produce) datagrams from a (remote) socket and it's entirely up to you how you process these datagrams.

However, considering the way your question is phrased, you're probably looking for a higher level abstraction. I'm not aware of any such library though. For the reasons above, I suppose this library might be a bad fit.

I hope this helps!
